/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Search;
import Hotel.HotelPage;
import java.sql.*;

/**
 *
 * @author getha
 */
public final class SearchResults extends javax.swing.JFrame {

    /**
     * Creates new form SearchResults
     * @param location
     * @param guest
     * @param room
     * @param checkin
     * @param checkout
     */
    public SearchResults(String location,int guest,int room,Date checkin,Date checkout,String userName,SearchPage sp) {
        this.location = location;
        this.guests = guest;
        this.rooms = room;
        this.checkin = checkin;
        this.checkout = checkout;
        this.userName = userName;
        this.back = sp;
        initComponents();
<<<<<<< HEAD
        setComponent();
        searchresult(this);
=======
        searchResult(this);
>>>>>>> bb03ec3fd7279d42826cc63c9db502d0173af9d6
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pic1 = new javax.swing.JLabel();
        HotelName1 = new javax.swing.JLabel();
        PricePerNight1 = new javax.swing.JLabel();
        TotalPrice1 = new javax.swing.JLabel();
        Ratings1 = new javax.swing.JLabel();
        TotalRating1 = new javax.swing.JLabel();
        Proceed = new javax.swing.JButton();
        available1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        HotelName2 = new javax.swing.JLabel();
        PricePerNight2 = new javax.swing.JLabel();
        TotalPrice2 = new javax.swing.JLabel();
        Ratings2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Proceed2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        HotelName3 = new javax.swing.JLabel();
        PricePerNight3 = new javax.swing.JLabel();
        TotalPrice3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Proceed3 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        Pic1.setText("Pic");

        HotelName1.setText("Name");

        PricePerNight1.setText("Price per night: ");

        TotalPrice1.setText("Total Price:");

        Ratings1.setText("ratings");

        TotalRating1.setText("total number of ratings");

        Proceed.setText("Proceed");
        Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedActionPerformed(evt);
            }
        });

        available1.setText("Available/Waiting");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Pic1)
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PricePerNight1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HotelName1)
                    .addComponent(TotalPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ratings1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TotalRating1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(available1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(Proceed)
                        .addGap(62, 62, 62))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ratings1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalRating1)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Proceed)
                            .addComponent(available1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pic1)
                            .addComponent(HotelName1))
                        .addGap(40, 40, 40)
                        .addComponent(PricePerNight1)
                        .addGap(26, 26, 26)
                        .addComponent(TotalPrice1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel7.setText("Pic");

        HotelName2.setText("Name");

        PricePerNight2.setText("Price per night: ");

        TotalPrice2.setText("Total Price:");

        Ratings2.setText("ratings");

        jLabel12.setText("total number of ratings");

        Proceed2.setText("Proceed");
        Proceed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proceed2ActionPerformed(evt);
            }
        });

        jLabel34.setText("Available/Waiting");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(161, 161, 161)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PricePerNight2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HotelName2)
                    .addComponent(TotalPrice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ratings2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(Proceed2)
                        .addGap(62, 62, 62))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Ratings2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Proceed2)
                            .addComponent(jLabel34)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(HotelName2))
                        .addGap(40, 40, 40)
                        .addComponent(PricePerNight2)
                        .addGap(26, 26, 26)
                        .addComponent(TotalPrice2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel13.setText("Pic");

        HotelName3.setText("Name");

        PricePerNight3.setText("Price per night: ");

        TotalPrice3.setText("Total Price:");

        jLabel17.setText("ratings");

        jLabel18.setText("total number of ratings");

        Proceed3.setText("Proceed");
        Proceed3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proceed3ActionPerformed(evt);
            }
        });

        jLabel35.setText("Available/Waiting");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addGap(161, 161, 161)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PricePerNight3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HotelName3)
                    .addComponent(TotalPrice3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(Proceed3)
                        .addGap(62, 62, 62))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Proceed3)
                            .addComponent(jLabel35)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(HotelName3))
                        .addGap(40, 40, 40)
                        .addComponent(PricePerNight3)
                        .addGap(26, 26, 26)
                        .addComponent(TotalPrice3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HotelPage hotel = new HotelPage(this.userName,Integer.parseInt(Proceed.getActionCommand()),this.guests,this.rooms,this.checkin,this.checkout,TotalPrice1.getText(),this);
    }//GEN-LAST:event_ProceedActionPerformed

    private void Proceed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proceed2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HotelPage hotel = new HotelPage(this.userName,Integer.parseInt(Proceed.getActionCommand()),this.guests,this.rooms,this.checkin,this.checkout,TotalPrice2.getText(),this);
    }//GEN-LAST:event_Proceed2ActionPerformed

    private void Proceed3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proceed3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HotelPage hotel = new HotelPage(this.userName,Integer.parseInt(Proceed.getActionCommand()),this.guests,this.rooms,this.checkin,this.checkout,TotalPrice3.getText(),this);
    }//GEN-LAST:event_Proceed3ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        back.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     */
<<<<<<< HEAD
    private void setComponent(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hoteldb", "root", "");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM hotels");
            int i=0;
            while(rs.next()){
                switch(i){
                    case 0:
                        if(rs.getString("location").equals(location)){
                            HotelName1.setText(rs.getString("Hotel"));
                            PricePerNight1.setText("Pricer: "+rs.getString("Price"));
                            TotalPrice1.setText("20000");
                            Proceed.setActionCommand(rs.getString("hotelid"));
                        }
                        i++;
                        break;
                    case 1:
                        if(rs.getString("location").equals(location)){
                            HotelName2.setText(rs.getString("Hotel"));
                            PricePerNight2.setText("Pricer: "+rs.getString("Price"));
                            TotalPrice2.setText("21000");
                            Proceed2.setActionCommand(rs.getString("hotelid"));
                        }
                        i++;
                        break;
                    case 2:
                        if(rs.getString("location").equals(location)){
                            HotelName3.setText(rs.getString("Hotel"));
                            PricePerNight3.setText("Pricer: "+rs.getString("Price"));
                            TotalPrice3.setText("Total Price: "+TotalPrice);
                            Proceed3.setActionCommand(rs.getString("hotelid"));
                        }
                        i++;
                        break;
                }
            }
        }
        catch(ClassNotFoundException | SQLException e){
           System.out.println("ERROR");
        }
    }
    private void searchresult(SearchResults ob1) {
=======
    public void searchResult(SearchResults ob1) {
>>>>>>> bb03ec3fd7279d42826cc63c9db502d0173af9d6
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
<<<<<<< HEAD
        java.awt.EventQueue.invokeLater(() -> {
            ob1.setVisible(true);
=======
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ob1.setVisible(true);
            }
>>>>>>> bb03ec3fd7279d42826cc63c9db502d0173af9d6
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HotelName1;
    private javax.swing.JLabel HotelName2;
    private javax.swing.JLabel HotelName3;
    private javax.swing.JLabel Pic1;
    private javax.swing.JLabel PricePerNight1;
    private javax.swing.JLabel PricePerNight2;
    private javax.swing.JLabel PricePerNight3;
    private javax.swing.JButton Proceed;
    private javax.swing.JButton Proceed2;
    private javax.swing.JButton Proceed3;
    private javax.swing.JLabel Ratings1;
    private javax.swing.JLabel Ratings2;
    private javax.swing.JLabel TotalPrice1;
    private javax.swing.JLabel TotalPrice2;
    private javax.swing.JLabel TotalPrice3;
    private javax.swing.JLabel TotalRating1;
    private javax.swing.JLabel available1;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
    private String location;
    private int guests;
    private int rooms;
    private Date checkin;
    private Date checkout;
    private String userName;
    private int TotalPrice;
    private SearchPage back;
}
